"""Added new Column in Train Table

Revision ID: 6bbdfc7c0855
Revises: 
Create Date: 2024-10-06 18:56:35.459570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbdfc7c0855'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stations', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trains', schema=None) as batch_op:
        batch_op.drop_column('stations')

    # ### end Alembic commands ###
