"""remove new Column in Train Table

Revision ID: 9d41126572da
Revises: 6bbdfc7c0855
Create Date: 2024-10-06 18:58:00.514126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d41126572da'
down_revision = '6bbdfc7c0855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trains', schema=None) as batch_op:
        batch_op.drop_column('stations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stations', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
